### ISSUE TITLE
Minor feedback on inconsistencies

### ISSUE THREAD

**Issue by mattfelsen** [bluecadet/Cinder-BluecadetUtils#18]
Just posting a few things as I come across them...

- ImageManager calls getAssetPath() on the string passed in, whereas Font, Style, and Video managers don't
- Different load/setup names:
  - ImageManager::loadAllImagesInDirectory()
  - VideoManager::loadAllFromDir()
  - FontManager::setup()

**Comment by benjaminbojko** [comment]
Made the `ImageManager` more consistent with the other classes in #20. It now doesn't automagically call `getAssetPath()` and allows for recursive loading. The naming has also been matched with `VideoManager::loadAllFromDir()`. `FontManager` naming will prob rename at `setup()` because that's a one-time call, whereas you can call `loadAllFromDir()` on multiple directories.
